### ISSUE TITLE
Realmefy wont show on modules list

### ISSUE THREAD

**Issue by aaa123-dev** [Kartrexofficial/Realify-#1]
Hi, so ive installed realmefy through install from storage in magisks module section and everytime i tried to install it wont show up afterwards (im using realme c55) so is it that my device doesnt really tolerate with these kind of modules?

**Comment by Kartrexofficial** [comment]
Hi I am aware of it, Realmify doesn't supported on Official Magisk but The module will be Updated with New name and also support Official magisk In Next patch tomorrow!! if you want to share anything Feel free to open issue or Pm me on Telegram 😊

**Comment by aaa123-dev** [comment]
Ok, thanksss
